import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./Header";
import { getCurrentUser } from "@/lib/firebases/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="flex flex-col">
          <div className="flex">
            <div className="w-64 shrink-0">jjjj</div>
            <Header/>
          </div >
          {children}
        </div> */}
        {children}
      </body>
    </html>
  );
}
